### ISSUE TITLE
make it possible to override an existing mapping

### ISSUE THREAD

**Issue by mohamnag** [NoEnv/vertx-wiremongo#1]
in cases where a generic mapping used for satisfying all other tests, it should be possible to override that with a new mapping.

Let's say I have a mapping file for a specific DB call that is good enough for all other tests. Where as in a specific test I want to change that mapping to test a failure case or any other functionality.  Currently this is not possible as the mapping added first has higher priority.
Solution would be letting any mapping that is added latest to have higher prio. this way one mapping used everywhere, might be overridden simply for one specific case.

**Comment by jo5ef** [comment]
implemented PR #2
