### ISSUE TITLE
provide "times(n)" feature

### ISSUE THREAD

**Issue by basalt79** [NoEnv/vertx-wiremongo#5]
every time the registered mapping is called, the number of count is increased, and if it is equals the provided "times", the mapping is removed automatically.

```java
wireMongo
  .findOne()
  .inCollection("person")
  .times(3)
  .withQuery(new JsonObject().put("_id", new JsonObject().put("$oid", personId)))
  .returns(new JsonObject().put("name", "Junit"));
```

**Comment by jo5ef** [comment]
implemented by https://github.com/NoEnv/vertx-wiremongo/pull/6
